### ISSUE TITLE
Свои папки с блоками

### ISSUE THREAD

**Issue by SeRGei93** [andreyryabin/sprint.editor#10]
возможность создавать дополнительные папки с блоками, сейчас все доп блоки лежат в папке my

**Comment by andreyryabin** [comment]
доступно с версии 3.4.1
Посмотрите такой формат оформления выпадающих списков блоков 
https://github.com/andreyryabin/sprint.editor/blob/master/install/admin/sprint.editor/settings/example.php

вам нужно сделать файл настроек модуля например local/admin/sprint.editor/settings/myexample.php

с такими настройками 

`<?php

$settings = [
    'title'                       => 'local/myexample.php',

    'block_toolbar' => [
        [
            'title'  => 'Блоки1',
            'blocks' => [
                'htag',
                'text',
            ],
        ],
        [
            'title'  => 'Блоки2',
            'blocks' => [
                'gallery',
                'image',
            ],
        ],
    ],
];`

**Comment by andreyryabin** [comment]
решено
