### ISSUE TITLE
не правильно работает отключение блоков

### ISSUE THREAD

**Issue by SeRGei93** [andreyryabin/sprint.editor#11]
По идее, если мы хотим показывать в шаблоне только определенный список блоков, мы заносим их в массив с ключом 'block_enabled'. Но так не работает и приходится перечислять блоки которые нам не нужны в ключе 'block_disabled'

**Comment by andreyryabin** [comment]
вспомнил что я такой трюк делал, быстрый хотфикс для вас

 'layout_enabled'  => [
       'layout_none',
    ],

мы включаем опцию layout_enabled тем что чем-то заполняем ее, 
но сетку указываем несуществующую и получается что все сетки отключены не затрагивая настройки в  block_disabled и block_enabled

**Comment by andreyryabin** [comment]
реализовать
если добавление блоков отключено, а в контенте ни одного блока который можно было как-то править - также показываем значение по умолчанию
