### ISSUE TITLE
Страница шаблонов

### ISSUE THREAD

**Issue by SeRGei93** [andreyryabin/sprint.editor#15]
Очень хорошо, было бы иметь возможность формировать свои шаблоны.
я это вижу как отдельную страницу в настройках редактора со списком и деталкой. В деталке можем накидать сетку и блоки + задать список блоков которые доступны в этом шаблоне
Дать возможность при создании новой страницы через редактор выбрать шаблон

**Comment by andreyryabin** [comment]
о каких шаблонах вы пишете? для публичной части или в админке?

**Comment by SeRGei93** [comment]
админка. обсудили с вами в телеграм

**Comment by andreyryabin** [comment]
решено
