### ISSUE TITLE
Доработка "Вложенные настройки"

### ISSUE THREAD

**Issue by qweik** [andreyryabin/sprint.editor#17]
Например вывод галерея фото:

1) списком
2) мозаикой
3) карусель
    3.1) по 1 на страницу
    3.2) по 2 на страницу
    3.3) по 3 на страницу

3.1 - 3.3 появляются вторым рядом, если выбран пункт 3

**Comment by andreyryabin** [comment]
нереалистично реализовать в текущем интерфейсе и програмном коде, к сожалению
