### ISSUE TITLE
Пустое значение по умолчанию

### ISSUE THREAD

**Issue by che7ovek** [andreyryabin/sprint.editor#18]
Как-то бы дать возможность у свойства редактора очистить значение по умолчанию до совсем пустого.
Сейчас оно сохраняется пустым, но при повторном открытии всё равно подставляется пустая сетка.

![изображение_2021-07-13_134006](https://user-images.githubusercontent.com/19785781/125438407-58de20fd-cdde-467f-ac9c-3159887c34d4.png)

**Comment by andreyryabin** [comment]
решено в 3.15.1
