### ISSUE TITLE
Настройка списка.

### ISSUE THREAD

**Issue by creio** [andreyryabin/sprint.editor#40]
Добавить возможность выбора в формате ключ = значение. как в дэфолтном св-ве строка, Выводить поле для описания значения.

![изображение](https://github.com/andreyryabin/sprint.editor/assets/20855126/ff624bf2-be1e-4e68-8bd2-92505599e040)

**Comment by andreyryabin** [comment]
Раскройте свою мысль детальнее, не понятно о чём речь

**Comment by creio** [comment]
> Раскройте свою мысль детальнее, не понятно о чём речь

Возможно так понятней.
![изображение](https://github.com/andreyryabin/sprint.editor/assets/20855126/a2488022-7a75-43dd-8c88-aefd4f9300ff)

**Comment by andreyryabin** [comment]
да, стало понятнее, такие правки, необходимые только вам, можно делать создавая новые блоки, возьмите за основу этот , скопируйте в my/my_lists и правьте на своё усмотрение
документация есть в вики, а общение в группе телеграма
