### ISSUE TITLE
Добавить подсветку области при перетаскивании в конструкторе

### ISSUE THREAD

**Issue by Ruslan-Aleev** [andreyryabin/sprint.editor#41]
Здравствуйте!

Было бы полезно, если бы при перетаскивании блоков была подсветка области куда блок встанет (может фоном, как на скрине, или рамкой). Это актуально для конструктора блоков, может еще где есть/будет "drag and drop".

![dd_bg](https://github.com/andreyryabin/sprint.editor/assets/12523676/3014adef-acf4-4257-aaed-5763a5a2f0aa)

p.s. В целом, это просто пожелание, если тяжело делать, то париться не стоит =)

**Comment by andreyryabin** [comment]
решено в 4.11.1
