### ISSUE TITLE
как то можно в блоке container, при вставке его в свой составной блок, прописать ему параметры, свой список блоков?

### ISSUE THREAD

**Issue by sirega** [andreyryabin/sprint.editor#44]
как то можно в блоке container, при вставке его в свой составной блок, прописать ему параметры, свой список блоков?

**Comment by sirega** [comment]
Ато сейчас мне приходится копировать этот блок, для того чтобы выбрать нужные блоки

    var blocklist = [
        {id: 'my_marking_type', title: 'Виды разметки'},
    ];

**Comment by andreyryabin** [comment]
Да, также как и в аккордеоне, создайте файл с настройками и задайте список блоков для контейнера 

https://github.com/andreyryabin/sprint.editor/blob/450f9813b8ac97f5d7128027b3e6544593c56905/install/admin/sprint.editor/settings/example.php#L160

**Comment by sirega** [comment]
спасибо посмотрел, вы вдохнули для меня в Битрикс новую жизнь. Не нашел возможности задать настройки для нескольких container внутри составоно, это возможно?

**Comment by andreyryabin** [comment]
да, в версии 4.13.1

вы можете описать настройки блоков  по ключу в котором они сохраняются внутри составного

допустим у вас составной блок с двумя контейнерами


`
sprint_editor.registerBlock('complex_2_container', function ($, $el, data) {
    var areas = [
        {
            "blockName": "container",
            "dataKey": "container_abc",
            "container": ".sp-area-1"
        },
        {
            "blockName": "container",
            "dataKey": "container_xyz",
            "container": ".sp-area-2"
        }
    ];
//...
});

`

Тогда их настройки можно описать так

`
$settings = [
    'complex_settings' => [

//название вашего составного блока
        'complex_2_container' => [


//название вашего составного блока
            'container_abc'  => [
                'blocks' => [
                    'type'  => 'hidden',
                    'value' => [
                        'htag' => 'htag',
                        'text' => 'text',
                    ],
                ],
            ],
            'container_xyz' => [
                'blocks' => [
                    'type'  => 'hidden',
                    'value' => [
                        'htag' => 'image',
                        'text' => 'video',
                    ],
                ],
            ],
        ],

`

**Comment by sirega** [comment]
спасибо большое
