### ISSUE TITLE
Добавление Превью изображения для блока

### ISSUE THREAD

**Issue by puzman** [andreyryabin/sprint.editor#7]
Возможность брать иконку и превью изображения из конфига блока и добавить ее в админку при выборе блока.

**Comment by andreyryabin** [comment]
Просят о задаче:

+ Igor Smirnov
+ Светлана Гущина

**Comment by andreyryabin** [comment]
решено в 4.0.0 https://bitbucket.org/andrey_ryabin/sprint.editor/wiki/CustomToolbar
