### ISSUE TITLE
Выбор типа контейнера

### ISSUE THREAD

**Issue by SeRGei93** [andreyryabin/sprint.editor#8]
Хотелось бы иметь возможность выбора типа контейнера перед вставкой колонок. 
к примеру
контейнер с заливкой
    колонка 1
    колонка 2

или

контейнер
    колонка 1
    колонка 2

**Comment by SeRGei93** [comment]
а лучше вообще, контейнеры без колонок внутри

**Comment by andreyryabin** [comment]
решено через блок контейнер
